- import_tasks: pgsql_version.yml

- name: Include distribution specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
        - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"
  tags:
    - always

- name: Include PostgreSQL version 13 specific variables
  ansible.builtin.include_vars: postgresql-13.yml
  when: pgsql_version.split('.')[0] == '13'

- name: Run tasks for {{ pgsqlrep_role }}
  ansible.builtin.include_tasks: "{{ pgsqlrep_role }}.yml"
  when: pgsqlrep_role != 'skip'
